apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple
spec:
  generators:
  - list:
      elements:
      - env: qa
      - env: staging
      - env: prod
  template:
    metadata:
      name: '{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/arpita-aa/gitops-cert-level-2-examples
        targetRevision: HEAD
        path: environment-promotion/envs/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{env}}
	 syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
