apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: simple
    namespace: argocd
spec:
    generators:
        list:
            elements:
            - env:  qa
            - env: staging
            - env: prod
    template:
        metadata:
            name: {{env}}
            namespace: argocd
        spec:
            project: default
            source:
                repoURL: https://github.com/arpita-aa/gitops-cert-level-2-examples
                path: ./environment-promotion/envs/{{env}}
                targetRevision: HEAD
            destination:
                server: https://kubernetes.default.svc
                namespace: {{env}}
            syncPolicy:
                syncOptions:
                - CreateNamespace=true
                automated:
                    selfHeal: true


